repos:
-   repo: https://github.com/homebysix/pre-commit-macadmin
    rev: v1.19.0
    hooks:
    -   id: check-autopkg-recipes
        args: ["--recipe-prefix=com.github.palantir."]
    -   id: check-plists
    -   id: forbid-autopkg-trust-info
