#!/bin/sh



########## variable-ing ##########



workingDir="${3}/private/tmp/log4j-sniffer"
binaryPath="${3}/usr/local/bin/log4j-sniffer"



########## main process ##########



# Remove old install resources if present.
if [ -e "$binaryPath" ]; then
  echo "Removing installed log4j-sniffer binary..."
  /bin/rm -fv "$binaryPath"
fi
if [ -e "$workingDir" ]; then
  echo "Removing old install resources..."
  /bin/rm -rfv "$workingDir"
fi
